<%@ Page Language="C#"  AutoEventWireup="true" MasterPageFile="~/Site.Master"  CodeBehind="Department.aspx.cs" Inherits="Wellness_Hospital.Department" %>


   <asp:Content ID="BodyContent"  ContentPlaceHolderID="MainContent" runat="server" >
         <div class="main_container" style=" width:400px; float:left;">
       
         <h3 style="text-align:center; font-family:Aharoni; font-style:oblique; font-size:30px; "> Department Details </h3>
       
              <div class="container-body col-md-12" >
          <div class="col-md-6 col-lg-6 col-sm-6"  style="left: -5px; top: 5px" >

            <table class="auto-style1">
                <tr>
                    <td style="width: 156px">
                        <asp:Label ID="lbDid" runat="server" Text="ID" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtDid" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td style="width: 156px">
                        <asp:Label ID="lbDname" runat="server" Text="Name" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtDname" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td style="width: 156px">
                        <asp:Label ID="lbDdepartmenthead" runat="server" Text="Department Head" CssClass="text" Width="147px"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtDdepartmenthead" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td style="width: 156px">
                        <asp:Label ID="lbDcontact" runat="server" Text="Contact No" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtDcontact" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td style="width: 156px">
                        <asp:Label ID="lbDfloor" runat="server" Text="Floor" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtDfloor" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td style="width: 156px"><asp:Button ID="btnDsubmit" runat="server" Text="Submit" CssClass="btn btn-warning" OnClick="btnDsubmit_Click"/></td>
                    <td>
                        <asp:Button ID="btnDcancle" runat="server" Text="Cancel" CssClass="btn btn-primary" OnClick="btnDcancle_Click"/></td>
                </tr>
            

                 <tr>
                    <td style="width: 156px">
                        <asp:Button ID="btnDupdate" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="btnDupdate_Click"/></td>
                    <td>
                        <asp:Button ID="btnDdelete" runat="server" Text="Delete" CssClass="btn btn-primary" OnClick="btnDdelete_Click"/></td>
                </tr>
            

            </table>
                                    </div>
                     </div>
            </div>

    <!--data grid view-->
<div class="col-lg-6 col-md-6" style="left:-4px; top:14px">
        <p>
            <asp:GridView ID="GridViewDepartment" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowDeleting="GridViewDepartment_RowDeleting" OnRowEditing="GridViewDepartment_RowEditing" OnSelectedIndexChanged="GridViewDepartment_SelectedIndexChanged">
            </asp:GridView>
        </p>
</div>  
   
         

 </asp:Content>
