<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Patient.aspx.cs" MasterPageFile="~/Site.Master"  Inherits="Wellness_Hospital.Patient" %>

 <asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
     <div class="main_container" style=" width:360px; float:left;">
      <h2 style="text-align:center; font-family:Aharoni; font-style:oblique; font-size:30px"> Patient Details </h2>
      
            <div class="container-body col-md-12"  >
              <div class="col-md-6 col-lg-6 col-sm-6" style="left: -5px; top: 5px">
            <table class="auto-style1" style="margin-top:15%,">
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPid" runat="server" Text="ID" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtId" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPname" runat="server" Text="Name" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtName" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPaddress" runat="server" Text="Address" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtAddress" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPcontact" runat="server" Text="Contact" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtContact" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPemail" runat="server" Text="Email" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtEmail" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPdob" runat="server" Text="Date Of Birth" CssClass="text" Width="114px"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:TextBox ID="txtDbo" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 140px">
                        <asp:Label ID="lbPgender" runat="server" Text="Gender" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3">
                        <asp:DropDownList ID="dropdownGender" runat="server" CssClass="txtbox" style="width:170px">
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                        </asp:DropDownList>
&nbsp;
                        </td>
                </tr>
                  
                 <tr>
                    <td style="width: 140px"><asp:Button ID="btnPsubmit" runat="server" Text="Submit" CssClass="btn btn-warning" OnClick="btnPsubmit_Click"/></td>
                    <td>
                        <asp:Button ID="btnPcancle" runat="server" Text="Cancel" CssClass="btn btn-primary" OnClick="btnPcancle_Click"/></td>
                </tr>
                  
                 <tr>
                    <td style="width: 140px">
                        <asp:Button ID="btnPupdate" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="btnPupdate_Click"/></td>
                    <td>
                        <asp:Button ID="btnPdelete" runat="server" Text="Delete" CssClass="btn btn-primary" OnClick="btnPdelete_Click"/></td>
                </tr>
            </table>
                  </div>
</div>
</div>

<!--data grid view-->
<div class="col-lg-6 col-md-6" style="left:-2px; top:14px">
        <p>
            <asp:GridView ID="GridViewPatient" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowDeleting="GridViewPatient_RowDeleting" OnRowEditing="GridViewPatient_RowEditing" OnSelectedIndexChanged="GridViewPatient_SelectedIndexChanged">
            </asp:GridView>
</div>

 </asp:Content>