<%@ Page Language="C#"  AutoEventWireup="true"  MasterPageFile="~/Site.Master"  CodeBehind="Test.aspx.cs" Inherits="Wellness_Hospital.Test" %>
   <asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
       <div class="main_container" style=" width:416px; float:left; height: 593px;">
         <h2 style="text-align:center;  font-family:Aharoni; font-style:oblique; font-size:30px"> Test Details</h2>
       
         <div class="container-body col-md-12" >
          <div class="col-md-6 col-lg-6 col-sm-6" style="left: -5px; top: 5px">
            <table class="auto-style1" style="margin-top:15%,">
                <tr>
                    <td>
                        <asp:Label ID="lbTid" runat="server" Text="ID" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style3" style="width: 144px" >
                        <asp:TextBox ID="txtTid" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                  
                </tr>
                <tr>
                    <td class="auto-style3" style="width: 144px" >
                        <asp:Label ID="lbTname" runat="server" Text="Name" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style2" >
                        <asp:TextBox ID="txtTname" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                  <tr>
                    <td class="auto-style3" style="width: 144px">
                        <asp:Label ID="lbTinvestigated" runat="server" Text="Investigated By" CssClass="text" Width="136px"></asp:Label>
                    </td>
                    <td class="auto-style2">
                        <asp:TextBox ID="txtTinvestigated" runat="server" CssClass="txtbox"></asp:TextBox>
                      </td>
                </tr>
                  <tr>
                    <td class="auto-style3" style="width: 144px">
                        <asp:Label ID="lbTdiagnosis" runat="server" Text="Diagnosis Details" CssClass="text" Width="143px"></asp:Label>
                    </td>
                    <td class="auto-style2" style="width: 110px">
                        <asp:TextBox ID="txtTdiagnosis" runat="server" CssClass="txtbox" Height="50px" TextMode="MultiLine"></asp:TextBox>
                      </td>
                </tr>
                  <tr>
                    <td class="auto-style3" style="width: 144px">
                        <asp:Label ID="lbTresult" runat="server" Text="Result" CssClass="text"></asp:Label>
                    </td>
                    <td class="auto-style2" style="width: 110px">
                        <asp:TextBox ID="txtTresult" runat="server" CssClass="txtbox" Height="50px" TextMode="MultiLine"></asp:TextBox>
                      </td>
                </tr>
                 <tr>
                    <td style="width: 144px"><asp:Button ID="btnTsubmit" runat="server" Text="Submit" CssClass="btn btn-warning" OnClick="btnTsubmit_Click"/></td>
                    <td style="width: 110px">
                        <asp:Button ID="btnTcancel" runat="server" Text="Cancel" CssClass="btn btn-primary" OnClick="btnTcancel_Click"/></td>
                </tr>
                 <tr>
                    <td style="width: 144px">
                        <asp:Button ID="btnTupdate" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="btnTupdate_Click"/></td>
                    <td style="width: 110px">
                        <asp:Button ID="btnTdelete" runat="server" Text="Delete" CssClass="btn btn-primary" OnClick="btnTdelete_Click"/></td>
                </tr>
            </table>
                                   </div>
                     </div>
            </div>

    <!--data grid view-->
<div class="col-lg-6 col-md-6" style="left:-2px; top:14px">
        <p>
            <asp:GridView ID="GridViewTest" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowDeleting="GridViewTest_RowDeleting" OnRowEditing="GridViewTest_RowEditing" OnSelectedIndexChanged="GridViewTest_SelectedIndexChanged">
            </asp:GridView>
        </p>
</div>
     </asp:Content>
