<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Ward.aspx.cs" Inherits="Wellness_Hospital.Ward" %>

 <asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
         <div class="main_container" style=" width:400px; float:left;">
        <h2   style="text-align:center; font-family:Aharoni; font-style:oblique; font-size:30px" > Ward Details </h2>
              
              <div class="container-body col-md-12"  >
          <div class="col-md-6 col-lg-6 col-sm-6" style="left: -5px; top: 5px">
             
            <table class="auto-style1">
                <tr>
                    <td class="auto-style2" style="width: 137px">
                        <asp:Label ID="lbWid" runat="server" Text="ID" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtWId" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 137px">
                        <asp:Label ID="lbWname" runat="server" Text="Name" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtWname" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 137px">
                        <asp:Label ID="lbWfloor" runat="server" Text="Floor" CssClass="text"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtWfloor" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                  <tr>
                    <td class="auto-style2" style="width: 137px">
                        <asp:Label ID="lbWcontact" runat="server" Text="Contact No" CssClass="text" Width="114px"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtWcontact" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2" style="width: 137px">
                        <asp:Label ID="lbWwardhead" runat="server" Text="Ward Head" CssClass="text" Width="114px"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="txtWwardhead" runat="server" CssClass="txtbox"></asp:TextBox>
                    </td>
                </tr>
                 <tr>
                    <td style="width: 137px"><asp:Button ID="btnWsubmit" runat="server" Text="Submit" CssClass="btn btn-warning" OnClick="btnWsubmit_Click1"/></td>
                    <td>
                        <asp:Button ID="btnWcancel" runat="server" Text="Cancel" CssClass="btn btn-primary" OnClick="btnWcancel_Click"/></td>
                </tr>
                 <tr>
                    <td style="width: 137px">
                        <asp:Button ID="btnWupdate" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="btnWupdate_Click"/></td>
                    <td>
                        <asp:Button ID="btnWdelete" runat="server" Text="Delete" CssClass="btn btn-primary" OnClick="btnWdelete_Click"/></td>
                </tr>
            </table>
                                  </div>
                     </div>
            </div>

    <!--data grid view-->
<div class="col-lg-6 col-md-6" style="left:-2px; top:14px">
    <p>
        <asp:GridView ID="GridViewWard" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridViewWard_SelectedIndexChanged" OnRowDeleting="GridViewWard_RowDeleting" OnRowEditing="GridViewWard_RowEditing">
        </asp:GridView>
        </p>
</div>
 </asp:Content>